name: Test wasip1

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions: {}

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.24.x,1.25.x]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

    - name: Install Go
      uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
      with:
        go-version: ${{ matrix.go-version }}

    - name: Install wasirun
      run: |
        go install github.com/stealthrocket/wasi-go/cmd/wasirun@v0.8.0

    - name: Test
      run: make wasitest
