name: Test wasip1

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions: {}

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.23.x,1.24.x]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Install Go
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
      with:
        go-version: ${{ matrix.go-version }}

    - name: Install wasirun
      run: |
        go install github.com/stealthrocket/wasi-go/cmd/wasirun@latest

    - name: Test
      run: make wasitest
